theme = "gruvbox-light"
icons = "awesome5"

[[block]]
block = "notmuch"
query = "tag:unread"
threshold_warning = 1
threshold_critical = 10
name = "A"

#[[block]]
#block = "maildir"
#interval = 60
#inboxes = ["/home/.mail/*/Inbox"]
#threshold_warning = 1
#threshold_critical = 10
#display_type = "new"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 60
format = "%a %d.%m. %R"
