# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];
  boot.initrd.luks.devices.cryptlvm.device = "/dev/disk/by-uuid/67e3aaef-3637-48ac-b51c-db4fe058acb5";
  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c30bfa9c-1c56-4073-83df-ee6d5af7604b";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/DAF0-2B31";
      fsType = "vfat";
    };
  swapDevices =
    [ { device = "/dev/disk/by-uuid/0382a99a-2206-4597-9075-bfca3e050456"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
